### ISSUE TITLE
SSR doesnt work by default?

### ISSUE THREAD

**Issue by Firman95** [1isten/vue-cli-ssr#1]
I run the project with `npm run serve`, when I look into the source of `localhost:8081`, no html code showed inside `<div id="app">`.

**Comment by 1isten** [comment]
No, `npm run serve` only starts a dev server. I didn't change this so it is vue-cli's default behavior. But I think it's good for development.

You have to run `node app.js` (i.e. `npm run start`, after `npm run build`) to start the express server which is configured to do SSR.
